import type { Workflow } from '@comfy-commerce/shared'

import { BUILTIN_GRAPH_WORKFLOWS } from './builtin-graphs.js'

/**
 * Built-in workflows — the curated defaults every install ships with. They are
 * full ComfyUI graphs baked from saved workflows: they run and download like a
 * user workflow, but are immutable. See builtin-graphs.ts (generated by
 * scripts/bake-builtins.ts).
 */

export const BUILTIN_PREFIX = 'builtin:'

/** Common built-in shape, minus the engine-computed compatibility. */
type BuiltinBase = Omit<Workflow, 'compat'>

/** A built-in workflow — a baked ComfyUI graph. */
export interface BuiltinGraphWorkflow extends BuiltinBase {
  /** Original DB id, kept so historical runs stored against it still resolve. */
  legacyId: string
  /** Executable (API-format) graph. */
  graph: Record<string, unknown>
  /** Editor-format original for download; null ⇒ only the API graph exists. */
  rawGraph: Record<string, unknown> | null
  inputNodeId: string
  outputNodeId: string
}

export type BuiltinWorkflow = BuiltinGraphWorkflow

/** Display order for the built-in list — drives the Workflows page and the run
 *  picker. Ids not listed fall to the end in their generated order. */
const DISPLAY_ORDER = [
  'builtin:subtle-grade',
  'builtin:t-shirt-shoot-x3',
  'builtin:relighting',
  'builtin:change-aspect-ratio',
  'builtin:fit-to-768px',
  'builtin:nano-banana-2-generic',
  'builtin:gpt-image-2-generic',
  'builtin:amazon-spec-product-image',
  'builtin:tripo-p1-image-to-3d',
]
const orderRank = (id: string) => {
  const i = DISPLAY_ORDER.indexOf(id)
  return i === -1 ? DISPLAY_ORDER.length : i
}

/**
 * Thumbnail media overrides, applied over the generated fields so re-baking
 * builtin-graphs.ts never drops them. Shipped in web/public/builtins:
 *  - The Tripo 3D card uses a short looping video of a rotating model (its
 *    baked source has no still).
 *  - The multi-MB preview PNGs are swapped for pre-downscaled 768px-wide
 *    copies (builtins/thumbs, `sips --resampleWidth 768`) so the first
 *    /workflows visit doesn't fetch + decode ~18MB of full-resolution images
 *    during the page transition. The originals stay alongside.
 */
const THUMBNAIL_OVERRIDES: Record<string, Partial<Pick<Workflow, 'imageUrl' | 'compareImageUrl'>>> = {
  'builtin:subtle-grade': {
    imageUrl: '/builtins/thumbs/subtle-grade.png',
    compareImageUrl: '/builtins/thumbs/subtle-grade-compare.png',
  },
  'builtin:t-shirt-shoot-x3': {
    imageUrl: '/builtins/thumbs/t-shirt-shoot-x3.png',
  },
  'builtin:change-aspect-ratio': {
    imageUrl: '/builtins/thumbs/change-aspect-ratio.png',
    compareImageUrl: '/builtins/thumbs/change-aspect-ratio-compare.png',
  },
  'builtin:fit-to-768px': {
    imageUrl: '/builtins/thumbs/fit-to-768px.png',
  },
  'builtin:nano-banana-2-generic': {
    compareImageUrl: '/builtins/thumbs/nano-banana-2-generic-compare.png',
  },
  'builtin:tripo-p1-image-to-3d': {
    imageUrl: '/builtins/tripo-p1-image-to-3d.mp4',
  },
}

export const BUILTIN_WORKFLOWS: BuiltinWorkflow[] = [...BUILTIN_GRAPH_WORKFLOWS]
  .map((w) => ({ ...w, ...THUMBNAIL_OVERRIDES[w.id] }))
  .sort((a, b) => orderRank(a.id) - orderRank(b.id))

/** Resolve a built-in by its id, or by its legacy (old DB) id. */
export function getBuiltin(workflowId: string): BuiltinWorkflow | undefined {
  return BUILTIN_WORKFLOWS.find((w) => w.id === workflowId || w.legacyId === workflowId)
}
