/**
 * One-off: bake the user's saved "My workflows" into shipped built-in workflows.
 *
 * Reads every row from the workflows table, copies each thumbnail into
 * web/public/builtins/, and emits server/src/workflows/builtin-graphs.ts with the
 * executable graph + editor-format rawGraph (for download). Pass --delete to then
 * remove the baked rows from the DB (their content now lives in code).
 *
 *   pnpm tsx scripts/bake-builtins.ts            # generate + copy thumbnails
 *   pnpm tsx scripts/bake-builtins.ts --delete   # also delete the baked rows
 */
import Database from 'better-sqlite3'
import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const dbPath = path.join(repoRoot, 'server/data/comfy-commerce.sqlite')
const assetsDir = path.join(repoRoot, 'server/data/assets')
const publicDir = path.join(repoRoot, 'web/public/builtins')
const outModule = path.join(repoRoot, 'server/src/workflows/builtin-graphs.ts')

const slugify = (name: string): string =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

interface Row {
  id: string
  name: string
  description: string
  graph: string
  raw_graph: string | null
  input_node_id: string
  output_node_id: string
  params: string
  fixed_inputs: string
  node_count: number
  image_asset_id: string | null
  compare_image_asset_id: string | null
}

const db = new Database(dbPath)
db.pragma('busy_timeout = 5000')

const assetFilename = db.prepare<[string], { filename: string }>(
  'SELECT filename FROM assets WHERE id = ?',
)

/** Copy an asset by id into web/public/builtins/<slug><suffix>.<ext>; return its public URL. */
function copyThumb(assetId: string | null, slug: string, suffix: string): string | null {
  if (!assetId) return null
  const row = assetFilename.get(assetId)
  if (!row) return null
  const src = path.join(assetsDir, row.filename)
  if (!existsSync(src)) return null
  const ext = path.extname(row.filename) || '.png'
  const file = `${slug}${suffix}${ext}`
  copyFileSync(src, path.join(publicDir, file))
  return `/builtins/${file}`
}

mkdirSync(publicDir, { recursive: true })

const rows = db
  .prepare<[], Row>('SELECT * FROM workflows ORDER BY created_at')
  .all()

// Safety: never clobber the committed module from an empty/already-baked DB.
if (rows.length === 0) {
  console.log('No workflows in the DB — leaving builtin-graphs.ts untouched.')
  db.close()
  process.exit(0)
}

const baked = rows.map((row) => {
  const slug = slugify(row.name)
  return {
    id: `builtin:${slug}`,
    legacyId: row.id,
    name: row.name,
    description: row.description,
    source: 'builtin' as const,
    params: JSON.parse(row.params),
    fixedInputs: JSON.parse(row.fixed_inputs),
    nodeCount: row.node_count,
    imageUrl: copyThumb(row.image_asset_id, slug, ''),
    compareImageUrl: copyThumb(row.compare_image_asset_id, slug, '-compare'),
    createdAt: '2026-01-01T00:00:00.000Z',
    inputNodeId: row.input_node_id,
    outputNodeId: row.output_node_id,
    graph: JSON.parse(row.graph),
    rawGraph: row.raw_graph ? JSON.parse(row.raw_graph) : null,
  }
})

const header = `// GENERATED by scripts/bake-builtins.ts — do not edit by hand.
// The user's saved workflows, baked into shipped built-ins.
import type { BuiltinGraphWorkflow } from './builtins.js'

export const BUILTIN_GRAPH_WORKFLOWS: BuiltinGraphWorkflow[] = `
writeFileSync(outModule, `${header}${JSON.stringify(baked, null, 2)}\n`)
console.log(`Wrote ${baked.length} built-in graphs → ${path.relative(repoRoot, outModule)}`)
for (const b of baked) console.log(`  ${b.id}${b.rawGraph ? '' : '  (api-format only)'}`)

if (process.argv.includes('--delete')) {
  const del = db.prepare('DELETE FROM workflows WHERE id = ?')
  const tx = db.transaction((ids: string[]) => ids.forEach((id) => del.run(id)))
  tx(rows.map((r) => r.id))
  console.log(`Deleted ${rows.length} rows from the workflows table.`)
}

db.close()
